### ISSUE TITLE
template + innerHTML VS DOMParser for fragment

### ISSUE THREAD

**Issue by JounQin** [syntax-tree/hast-util-from-html-isomorphic#2]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Which solution should be preferred?

### Solution

https://github.com/rehypejs/rehype-dom/pull/19

### Alternatives

N/A

**Comment by remcohaszing** [comment]
Hey, long time no see! :wave: 

I think the method used here in `hast-util-from-html-isomorphic` is relatively elegant. As far as I can tell it works fine. I would love to hear about cases where the other method is preferred though.

**Comment by wooorm** [comment]
I believe the linked issue explains more. Using a template in the current document sends HTTP requests: https://github.com/rehypejs/rehype-dom/issues/18.

**Comment by remcohaszing** [comment]
I am seeing a network request when using the code from https://stackoverflow.com/questions/12747350/using-documentfragment-to-parse-html-without-sending-http-requests (linked from https://github.com/rehypejs/rehype-dom/issues/18), but not when using a `<template>` tag as is used in the current approach.

**Comment by wooorm** [comment]
Hmm, funky. Might be the template tag?

**Comment by remcohaszing** [comment]
Yes, I think so.

This HTML document triggers a request:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <img src="./image.png" />
  </body>
</html>
```

This one doesn’t

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <template>
      <img src="./image.png" />
    </template>
  </body>
</html>
```

**Comment by wooorm** [comment]
@JounQin Then I think this can be closed?

**Comment by wooorm** [comment]
Closing, seems fine!

**Comment by JounQin** [comment]
Sure, I missed this issue for a long time.

I'm not for sure will `template` + `innerHTML` be XSSed? But I think `DOMParser` will never be?
